name: CI

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

defaults:
  run:
    shell: bash

jobs:
  lint:
    name: CI
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - &checkout
        uses: actions/checkout@v6

      - &setup-pnpm
        uses: pnpm/action-setup@v4

      - &setup-node
        uses: actions/setup-node@v6
        with:
          node-version-file: .node-version
          cache: pnpm

      - &install-deps
        name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Check formatting
        run: pnpm run format --check

      - name: Lint
        run: pnpm run lint

  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - *checkout
      - *setup-pnpm
      - *setup-node
      - *install-deps

      - name: Build
        run: pnpm run build:ci
